/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 zuvy-baby.glb -T 
Files: zuvy-baby.glb [1.32MB] > D:\Test Project\zuvara-frontend\public\models\zuvy-baby-transformed.glb [189.78KB] (86%)
*/

import * as THREE from "three";
import React from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    eyebrow002: THREE.Mesh;
    zuvera_body_v008001: THREE.Mesh;
    diaper002: THREE.Mesh;
    Object_2001: THREE.Mesh;
    Object_3: THREE.Mesh;
    Object_3001: THREE.Mesh;
  };
  materials: {
    ["Material.003"]: THREE.MeshStandardMaterial;
    ["Material.001"]: THREE.MeshStandardMaterial;
    ["diaper-texture"]: THREE.MeshStandardMaterial;
    ["Material.006"]: THREE.MeshStandardMaterial;
    ["Material.007"]: THREE.MeshStandardMaterial;
    BodyB_mat: THREE.MeshStandardMaterial;
  };
};

export function Model(props: React.JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/zuvy-baby-transformed.glb"
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.eyebrow002.geometry}
        material={materials["Material.003"]}
        position={[3.935, 6.209, 5.397]}
        rotation={[-Math.PI, 0, 0]}
        scale={0.1}
      />
      <mesh
        geometry={nodes.zuvera_body_v008001.geometry}
        material={materials["Material.001"]}
        position={[3.9, 3.431, 4.384]}
        rotation={[-Math.PI, 0, 0]}
        scale={0.1}
      />
      <mesh
        geometry={nodes.diaper002.geometry}
        material={materials["diaper-texture"]}
        position={[3.893, 2.25, 4.169]}
        rotation={[-Math.PI, 0, 0]}
        scale={[0.101, 0.106, 0.099]}
      />
      <mesh
        geometry={nodes.Object_2001.geometry}
        material={materials["Material.006"]}
        position={[4.503, 5.615, 5.051]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.251}
      />
      <mesh
        geometry={nodes.Object_3.geometry}
        material={materials["Material.007"]}
        position={[4.503, 5.615, 5.051]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.251}
      />
      <mesh
        geometry={nodes.Object_3001.geometry}
        material={materials.BodyB_mat}
        position={[3.892, 6.439, 4.215]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.001}
      />
    </group>
  );
}

useGLTF.preload("/models/zuvy-baby-transformed.glb");